title:              Nick's Game Blog
email:              blust.nick@gmail.com
description:        Displaying my latest Game Development Endeavours
author:             Dominik Baumann
baseurl:            ""
url:                "https://nickblust.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    NickBlust
#facebook_username:  StartBootstrap
#instagram_username:  
linkedin_username: dominik-baumann-53128a323

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-3CBDR9LJNS # out your google-analytics code

# Build settings
markdown:           kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
